const memoryCards = [
   {
      id: "b44717bb-e0c5-49ca-af1d-4c34df45a3a6",
      name: "Kevin Alcalen",
      email: "kevo@yahoo.com",
      phone: "702-555-0729",
      availability: {
         monday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
         tuesday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
         wednesday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
         thursday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },

         friday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
         saturday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
         sunday: {
            am6: true,
            am7: true,
            am8: true,
            am9: false,
            am10: false,
            am11: false,
            pm12: false,
            pm1: false,
            pm2: false,
            pm3: false,
            pm4: false,
            pm5: false,
            pm6: false,
            pm7: false,
            pm8: false,
            pm9: false,
            pm10: false,
            pm11: false,
         },
      },
   },
];

export default memoryCards;
